extends Node2D

var TYPE				# ATTACK, ACTION, ITEM, SPARE, DEFENSE
var DECIDER				# KRIS, SUSIE, RALSEI
var ITEM_CODE = null	# TOP_CAKE, TREFDWITCH, CHALK...
var ACTION_CODE = null  # PERUETT, SPELL, HYPNOTIZE...
var VICTIM				# JEVIL, SPAMTON, KRIS, SUSIE, RALSEI
